algoritmo "Menor"
// Função :
// Autor :
// Data : 15/9/2015
// Seção de Declarações 
var
N1,N2,N3:real
inicio
// Seção de Comandos 
escreva("Número 1: ")
leia(N1)
escreva("Número 2: ")
leia(N2)
escreva("Número 3: ")
leia(N3)
se N1<N2 entao
se N1<N3 entao
escreva("Número 1")
senao
se N2<N3 entao
escreva("Número 2")
senao
escreva("Número 3")
fimse
fimse
fimse
fimalgoritmo
