algoritmo "Operaçoes"
// Função :
// Autor :
// Data : 15/9/2015
// Seção de Declarações 
var
A,B,R1,R2,R3,R4:real
inicio
// Seção de Comandos
escreva("A: ")
leia(A)
escreva("B: ")
leia(B)
se A>0 entao
se B>0 entao
R1<-A+B
R2<-A-B
R3<-A*B
R4<-A/B
escreval("R1: ",R1)
escreval("R2: ",R2)
escreval("R3: ",R3)
escreval("R4: ",R4)
senao
escreva("Nao esta no conjunto")
fimse
senao
escreva("Nao esta no conjunto")
fimse
fimalgoritmo
