algoritmo "CP"
// Função :
// Autor :
// Data : 15/9/2015
// Seção de Declarações 
var
C,P:inteiro
inicio
// Seção de Comandos
escreva("Preço Produto: ")
leia(P)
escreva("Código Produto: ")
leia(C)
se C=1 entao
escreva("Sul")
senao
se C=2 entao
escreva("Norte")
senao
se C=3 entao
escreva("Leste")
senao
se C=4 entao
escreva("Oeste")
senao
escreva("Produto Importado")
fimse
fimse
fimse
fimse
fimalgoritmo
