algoritmo "Classe"
// Função :
// Autor :
// Data : 15/9/2015
// Seção de Declarações 
var
X:inteiro
inicio
// Seção de Comandos
escreva("Idade: ")
leia(X)
se X>=55 entao
escreva("Idoso")
senao
se X>=20 entao
escreva("Adulto")
senao
se X>=12 entao
escreva("Adolescente")
senao
se (X>=2)e(X>0)entao
escreva("Criança")
senao
escreva("Não nasceu")
fimse
fimse
fimse
fimse
fimalgoritmo
