algoritmo "52"
// Função :
// Autor :
// Data : 10/11/2015
// Seção de Declarações 
var
C,M,Em:real
inicio
// Seção de Comandos
escreva("Capital= ")
leia(C)
escreva("Meses de Aluguel= ")
leia(M)
enquanto C>0 faca
Em<-C*(1+(20/100)*M)
escreval(C)
escreval(M)
escreval("Emprestimo= ",Em)
escreva("Capital= ")
leia(C)
escreva("Meses de Aluguel= ")
leia(M)
fimenquanto
fimalgoritmo
