algoritmo "CLASSIFICAÇÂO"
// Função :
// Autor :
// Data : 15/9/2015
// Seção de Declarações 
var
I:inteiro
inicio
// Seção de Comandos
escreva("Idade: ")
leia(I)
se I>18 entao
escreva("Sênior")
senao
se I>14 entao
escreva("Juvenil B")
senao
se I>11 entao
escreva("Juvenil A")
senao
se I>8 entao
escreva("Infantil B")
senao
se I>5 entao
escreva("Infantil A")
senao
escreva("Sem classificaçao")
fimse
fimse
fimse
fimse
fimse
fimalgoritmo
